.TH glassgui 1 "September 2015" Linux "Linux Audio Manual"
.SH NAME
glassgui \- GUI front-end for glasscoder(1) audio encoder

.SH SYNOPSIS
glassgui [OPTIONS]

.SH DESCRIPTION
\fBGlassgui\fP is a GUI front end for the glasscoder(1) audio encoder.
It provides a convienent and discoverable means for creating and saving
glasscoder(1) invocations as well as an instance management system for
saving multiple sets of configurations on the local system.

.SH OPTIONS
.TP
.B --delete-instance=<\fIname\fP>
Delete the <\fIname\fP> instance from storage and then exit.

.TP
.B --instance-name=<\fIname\fP>
Load and save settings from/to the <\fIname\fP> instance.

.TP
.B --list-instances
Print the list of saved instances to standard output and then exit.

.SH AUTHOR
Fred Gleason <fredg@paravelsystems.com>
.SH SEE ALSO
.BR glasscoder (1)









