'\" t
.\"     Title: glasscoder
.\"    Author: Fred Gleason <fredg@paravelsystems.com>
.\" Generator: DocBook XSL-NS Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 04/06/2016
.\"    Manual: Linux Audio Manual
.\"    Source: October 2015
.\"  Language: English
.\"
.TH "GLASSCODER" "1" "04/06/2016" "October 2015" "Linux Audio Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
glasscoder \- Minimalist audio encoder for live streaming
.SH "SYNOPSIS"
.HP \w'\fBglasscoder\fR\ 'u
\fBglasscoder\fR [\fIOPTIONS\fR]
.br

.SH "DESCRIPTION"
.PP
\fBglasscoder\fR(1)
is an audio encoder that is capable of generating live streams using a variety of formats and sending them to an Icecast or Shoutcast audio streaming server or posting them as HTTP Live Streams [HLS]\&.
.PP
\fBglasscoder\fR(1)
has no GUI or configuration file components at all; its sole \*(Aquser interface\*(Aq is its command\-line invocation\&.
.SH "OPTIONS"
.PP
\fB\-\-audio\-atomic\-frames\fR
.RS 4
Emit a stream consisting of self\-contained frames \-\-e\&.g\&. by disabling the MPEG\-1 bit reservoir\&. Useful mostly for debugging\&.
.RE
.PP
\fB\-\-audio\-bitrate=\fR\fIkbps\fR
.RS 4
The constant stream data rate in kilobits per second\&. Default value is
\fB128\fR\&. Use of this option is mutually exclusive with that of the
\fB\-\-audio\-quality\fR
option (see below)\&.
.RE
.PP
\fB\-\-audio\-channels=\fR\fIchans\fR
.RS 4
The number of audio channels to use\&. Valid values are
\fB1\fR
or
\fB2\fR\&. Default value is
\fB2\fR\&.
.RE
.PP
\fB\-\-audio\-device=\fR\fItype\fR
.RS 4
The type of audio device to use\&. The default value is
\fBJACK\fR\&. See the
\fBDEVICE OPTIONS\fR
section (below) for the options appropriate for each audio device type\&. Valid values are:
.PP
\fBALSA\fR
.RS 4
The Advanced Linux Sound Architecture\&.
.RE
.PP
\fBASIHPI\fR
.RS 4
AudioScience HPI\&.
.RE
.PP
\fBFILE\fR
.RS 4
Stream directly from a file\&.
.RE
.PP
\fBJACK\fR
.RS 4
The Jack Audio Connection Kit\&.
.RE
.RE
.PP
\fB\-\-audio\-format=\fR\fIfmt\fR
.RS 4
The audio encoding format to use\&. The default value is
\fBVORBIS\fR\&. Valid
\fIfmt\fR
values are:
.PP
\fBAAC\fR
.RS 4
MPEG\-2 Advanced Audio Coding (Main Profile)
.RE
.PP
\fBAACP\fR
.RS 4
MPEG\-4 Advanced Audio Coding (High Efficiency Profile)
.RE
.PP
\fBMP2\fR
.RS 4
MPEG\-1/1\&.5 Layer 2
.RE
.PP
\fBMP3\fR
.RS 4
MPEG\-1/1\&.5 Layer 3
.RE
.PP
\fBPCM16\fR
.RS 4
PCM16 Uncompressed
.RE
.PP
\fBVORBIS\fR
.RS 4
Ogg Vorbis
.RE
.RE
.PP
\fB\-\-audio\-quality=\fR\fIqual\fR
.RS 4
Use variable bitrate streaming at the given audio quality\&.
\fIqual\fR
can be in the range
\fB0\&.0\fR
(lowest quality) to
\fB1\&.0\fR
(highest)\&. Use of this option is mutually exclusive with that of the
\fB\-\-audio\-bitrate\fR
option (see above)\&.
.RE
.PP
\fB\-\-audio\-samplerate=\fR\fIrate\fR
.RS 4
The audio sample rate to use for streaming\&. If the underlying audio layer is operating at a different sample rate, the input will be automatically resampled to this rate\&. Default value is
\fB44100\fR\&.
.RE
.PP
\fB\-\-errors\-to=\fR\fIdest\fR
.RS 4
Send error messages to
\fIdest\fR
(default standard error)\&. Valid destinations are:
.PP
\fBSTDERR\fR
.RS 4
Standard error\&.
.RE
.PP
\fBSYSLOG\fR
.RS 4
The system syslog service\&.
.RE
.PP
\fBSTDOUT\fR
.RS 4
Standard output,in machine readable format (useful for communication with another \*(Aqcontroller\*(Aq program)\&. See also the
\fB\-\-meter\-data\fR
option below\&.
.RE
.RE
.PP
\fB\-\-help\fR
.RS 4
Print a short usage message and exit\&.
.RE
.PP
\fB\-\-list\-codecs\fR
.RS 4
Print a list of available codecs and then exit\&.
.RE
.PP
\fB\-\-list\-devices\fR
.RS 4
Print a list of available source devices and then exit\&.
.RE
.PP
\fB\-\-meter\-data\fR
.RS 4
Output meter level updates on standard output\&. Useful for driving an external metering display\&.
.RE
.PP
\fB\-\-server\-auth=\fR[\fIusername\fR][\fB:\fR\fIpassword\fR]
.RS 4
The authentication parameters to use\&. This parameter has no default\&.
.RE
.PP
\fB\-\-server\-script\-down=\fR\fIcmd\fR
.RS 4
Run the command
\fIcmd\fR
when the connection enters the
disconnected
state\&.
.RE
.PP
\fB\-\-server\-script\-up=\fR\fIcmd\fR
.RS 4
Run the command
\fIcmd\fR
when the connection enters the
connected
state\&.
.RE
.PP
\fB\-\-server\-type=\fR\fItype\fR
.RS 4
The type of streaming server to use (default is
\fBIcecast2\fR)\&. Valid values for
\fItype\fR
are:
.PP
\fBFILE\fR
.RS 4
Local file
.RE
.PP
\fBFILEARCHIVE\fR
.RS 4
Local file archive\&. Stream to a set of files on the local system, starting a new file at the beginning of each hour\&.
.RE
.PP
\fBHLS\fR
.RS 4
HLS/HTTP Live Streaming
.RE
.PP
\fBIceCast2\fR
.RS 4
IceCast v2
.RE
.PP
\fBShout1\fR
.RS 4
Shoutcast v1
.RE
.PP
\fBShout2\fR
.RS 4
Shoutcast v2
.RE
.RE
.PP
\fB\-\-server\-url=\fR\fIurl\fR
.RS 4
The URL describing the server resource to stream to\&. This parameter has no default\&.
.RE
.PP
\fB\-\-stream\-aim=\fR\fIaim\fR
.RS 4
The AOL Instant Messenger ID to associate with the stream\&. There is no default value\&. This setting is used only by Shoutcast servers\&.
.RE
.PP
\fB\-\-stream\-description=\fR\fIstring\fR
.RS 4
The string to show as the stream description\&. There is no default value\&. This setting is used only by Icecast servers\&.
.RE
.PP
\fB\-\-stream\-genre=\fR\fIstring\fR
.RS 4
The string to show as the stream genre\&. There is no default value\&. This setting is used only by Icecast and Shoutcast servers\&.
.RE
.PP
\fB\-\-stream\-icq=\fR\fIicq\fR
.RS 4
The ICQ ID to associate with the stream\&. There is no default value\&. This setting is used only by Shoutcast servers\&.
.RE
.PP
\fB\-\-stream\-irc=\fR\fIirc\fR
.RS 4
The Internet Relay Chat ID to associate with the stream\&. There is no default value\&. This setting is used only by Shoutcast servers\&.
.RE
.PP
\fB\-\-stream\-name=\fR\fIstring\fR
.RS 4
The string to show as the stream name\&. There is no default value\&. This setting is used only by Icecast and Shoutcast servers\&.
.RE
.PP
\fB\-\-stream\-timestamp\-offset=\fR\fIoffset\fR
.RS 4
The offset to add to the value of stream timestamps, in seconds\&. Default value is
\fB0\fR\&. This setting is used only for HLS streams\&.
.RE
.PP
\fB\-\-stream\-url=\fR\fIurl\fR
.RS 4
The URL to show for a page giving more information about the stream\&. There is no default value\&. This setting is used only by Icecast and Shoutcast servers, but is ignored by Shoutcast v2 servers\&.
.RE
.PP
\fB\-\-verbose\fR
.RS 4
Increase verbosity level of information printed to standard error\&. WARNING: this may cause cleartext passwords to printed!
.RE
.PP
\fB\-\-version\fR
.RS 4
Output version information and exit\&.
.RE
.SH "DEVICE OPTIONS"
.PP
\fBAdvanced Linux Sound Architecture\fR (\fB\-\-audio\-device=\fR\fBALSA\fR)
.RS 4
.PP
\fB\-\-alsa\-device=\fR\fIdev\fR
.RS 4
The name of the ALSA device to use\&. If no
\fB\-\-audio\-device\fR
option is given, then the
\fBhw:0\fR
device will be used\&.
.RE
.RE
.PP
\fBAudioScience HPI\fR (\fB\-\-audio\-device=\fR\fB=ASIHPI\fR)
.RS 4
.PP
\fB\-\-asihpi\-adapter\-index=\fR\fIindex\fR
.RS 4
The index number of the audio adapter to use\&.
.RE
.PP
\fB\-\-asihpi\-input\-index=\fR\fIindex\fR
.RS 4
The number of the input audio stream to use on the specified adapter\&.
.RE
.PP
\fB\-\-asihpi\-input\-gain=\fR\fIgain\fR
.RS 4
The gain to apply to the input audio on the specified adapter in dB\&. Valid values are
\fB\-100\fR
to
\fB+20\fR
inclusive\&. Default value is
\fB0\fR\&.
.RE
.PP
\fB\-\-asihpi\-channel_mode=\fR\fImode\fR
.RS 4
The channel mode for the input audio on the specified adapter\&. The default value is
\fBNORMAL\fR\&. Valid values are:
.PP
\fBNORMAL\fR
.RS 4
Left signal goes to left channel, right signal goes to right channel\&.
.RE
.PP
\fBSWAP\fR
.RS 4
Left signal goes to right channel, right signal goes to left channel\&.
.RE
.PP
\fBLEFT\fR
.RS 4
Left signal goes to both left and right channels\&.
.RE
.PP
\fBRIGHT\fR
.RS 4
Right signal goes to both left and right channels\&.
.RE
.RE
.PP
\fB\-\-asihpi\-input\-source=\fR\fIsrc\-node\fR
.RS 4
The input source to use on the specified adapter\&. See the
\fBHPI Source Nodes\fR
section below for the list of valid
\fIsrc\-node\fR
values\&. The default value is
\fBLINEIN\fR\&.
.RE
.PP
\fB\-\-asihpi\-input\-type=\fR\fIsrc\-node\fR
.RS 4
The input type to use on the specified adapter\&. See the
\fBHPI Source Nodes\fR
section below for the list of valid
\fIsrc\-node\fR
values\&. The default value is
\fBLINEIN\fR\&.
.RE
.PP
\fBHPI Source Nodes\fR
.RS 4
The following values can used for the
\fB\-\-asihpi\-input\-source\fR
and
\fB\-\-asihpi\-input\-type\fR
options above:
.PP
\fBNONE\fR, \fBOSTREAM\fR
.RS 4
Internal output stream
.RE
.PP
\fBLINEIN\fR
.RS 4
Generic input signal
.RE
.PP
\fBAESEBU\fR
.RS 4
AES3 digital input
.RE
.PP
\fBTUNER\fR
.RS 4
Tuner
.RE
.PP
\fBRF\fR
.RS 4
RF input
.RE
.PP
\fBCLOCK\fR
.RS 4
Clock source
.RE
.PP
\fBBITSTREAM\fR
.RS 4
Raw bitstream
.RE
.PP
\fBMIC\fR
.RS 4
Microphone
.RE
.PP
\fBCOBRANET\fR
.RS 4
CobraNet
.RE
.PP
\fBANALOG\fR
.RS 4
Analog input
.RE
.PP
\fBADAPTER\fR
.RS 4
Adapter
.RE
.PP
\fBRTP\fR, \fBINTERNAL\fR
.RS 4
Device internal
.RE
.PP
\fBAVB\fR
.RS 4
AVB input
.RE
.RE
.RE
.PP
\fBDirect File Streaming\fR (\fB\-\-audio\-device=\fR\fBFILE\fR)
.RS 4
.PP
\fB\-\-file\-name=\fR\fIname\fR
.RS 4
The name of the file to stream\&. If no
\fB\-\-file\-name\fR
option is given, then the name of the file will be read from standard input\&.
.RE
.RE
.PP
\fBThe Jack Audio Connection Kit\fR (\fB\-\-audio\-device=\fR\fBJACK\fR)
.RS 4
.PP
\fB\-\-jack\-server\-name=\fR\fIname\fR
.RS 4
The name of the JACK server instance to use\&.
.RE
.PP
\fB\-\-jack\-client\-name=\fR\fIname\fR
.RS 4
The name of the JACK client to use\&. Default is
\fBglasscoder\fR\&.
.RE
.RE
.SH "NOTES"
.PP
HTTP Live Streams [HLS] require support for the HTTP
\fBPUT\fR
and
\fBDELETE\fR
methods on the publishing web server\&. See the GlassCoder documentation directory for a sample configuration for the Apache Web Server\&.
.SH "AUTHOR"
.PP
Fred Gleason <fredg@paravelsystems\&.com>
.SH "SEE ALSO"
.PP
\fBglassgui\fR(1),
\fBjackd\fR(1)
.SH "AUTHOR"
.PP
\fBFred Gleason\fR <\&fredg@paravelsystems\&.com\&>
.RS 4
Application Author
.RE
